django_project/content/urls.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <mukomalison@gmail.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__doc__ = ''
__license__ = ''
__copyright__ = ''

from django.conf.urls import url
from .views.home import HomeView
from .views.home import AboutUsView
from .views.success_story import (
    SuccessStoryList,
    SuccessStoryDetail)
from .views.under_development import UnderDevelopment
from .views.download_smartcare import DownloadFile

from .views.smartcare import (
    OverviewView,
    FunctionalModulesView,
    TechnologyStackView,
    DevelopmentPipelineView,
    TechnicalUpdatesView,
    DeploymentView,
    TrainingView
    )
from .views.sponsors import SponsorPartnerView


urlpatterns = [
    url(r'^$',
        HomeView.as_view(),
        name='home'),

    url(r'^overview/$',
        OverviewView.as_view(),
        name='overview'),

    url(r'^sponsors/$',
        SponsorPartnerView.as_view(),
        name='sponsorship'),

    url(r'^functional-modules$',
        FunctionalModulesView.as_view(),
        name='functional_modules'),

    url(r'^technology-stack/$',
        TechnologyStackView.as_view(),
        name='technology_stack'),

    url(r'^deployment-pipeline/$',
        DevelopmentPipelineView.as_view(),
        name='deployment_pipeline'),

    url(r'^technical-updates/$',
        TechnicalUpdatesView.as_view(),
        name='technical_updates'),

    url(r'^deployment$',
        DeploymentView.as_view(),
        name='deployment'),

    url(r'^training/$',
        TrainingView.as_view(),
        name='training'),

    url(r'^download/$',
        DownloadFile.as_view(),
        name='download'),
    url(r'^under-development/$',
        UnderDevelopment.as_view(),
        name='under_development'),
    url(r'^about/$',
        AboutUsView.as_view(),
        name='about'),
    url(r'^success/$',
        SuccessStoryList.as_view(),
        name='success'),
    url(r'^story/(?P<story_pk>\d+)/detail/$',
        SuccessStoryDetail.as_view(),
        name='success_detail')
]

django_project/core/urls.py
    # coding=utf-8
"""Project level url handler."""
from __future__ import absolute_import

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseServerError
from django.template import loader, Context
from rest_framework_swagger.views import get_swagger_view
from contactus import urls as contact_urls

admin.autodiscover()
handler404 = 'base.viewsets.error_views.custom_404'


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    See http://raven.readthedocs.org/en/latest/integrations/
        django.html#message-references

    :param request: Django request object.

    Templates: `500.html`
    Context: None
    """
    # You need to create a 500.html template.
    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render(Context({
        'request': request,
    })))

urlpatterns = [
    url(r'^', include('content.urls', namespace='content')),
    url('^contact/', include(contact_urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^site-admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^tracking/', include('tracking.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

admin.site.site_header = 'Pricetag website Admin'
admin.site.site_title = 'Pricetag website Admin'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/content/models/carousel_headers.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'


# coding=utf-8
"""Carousel header model definition.

"""

from django.db import models
from ordered_model.models import OrderedModel


class CarouselHeader(OrderedModel):
    """Carousel header model."""

    banner = models.ImageField(
        upload_to='banner'
    )

    description = models.TextField(
        blank=True,
        default='',
    )

    def __str__(self):
        return self.description

django_project/content/models/category.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'


from django.db import models
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=255,
    )

    description = RichTextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'category'
        verbose_name_plural = 'Categories'


    def __str__(self):
        return self.name

django_project/content/models/location.py
# coding: utf-8
__author__ = 'Alison Mukoma <alison@devsbranch.com>'
__license__ = 'GPL'
__copyright__ = 'devsbranch.com'

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Location(models.Model):
    name = models.CharField(
        _('Location Name'),
        max_length=255,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

django_project/content/models/manufacture.py
# coding: utf-8
__author__ = 'Alison Mukoma <alison@devsbranch.com>'
__license__ = 'GPL'
__copyright__ = 'devsbranch.com'

from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_countries.fields import CountryField


class Manufacture(models.Model):
    name = models.CharField(
        _('Manufacture Name'),
        max_length=255,
        null=True,
        blank=True,
    )
    country = CountryField(blank_label='(select country)')

    def __str__(self):
        return self.name

django_project/content/models/product.py
# coding: utf-8
__author__ = 'Alison Mukoma <alison@devsbranch.com>'
__license__ = 'GPL'
__copyright__ = 'devsbranch.com'

import os
from datetime import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf.global_settings import MEDIA_ROOT
from .category import Category
from .location import Location
from .manufacture import Manufacture
from .shop_owner import ShopOwner
from djmoney.models.fields import MoneyField


class Product(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=255,
        null=False,
        blank=False
    )
    code = models.CharField(
        _('Product Code'),
        max_length=255,
        null=True,
        blank=True
    )
    price = MoneyField(
        decimal_places=2,
        default=0,
        default_currency='ZMK',
        max_digits=11,
    )
    specifications = models.TextField(
        _('Specifications'),
        null=True,
        blank=True
    )
    description = models.TextField(
        _('Description'),
        null=True,
        blank=True,
    )
    is_available = models.BooleanField(
        _('Is product in stock?'),
        default=True
    )

    shop = models.ForeignKey(
        ShopOwner,
        on_delete=models.CASCADE,
        default=''
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    manufacture = models.ForeignKey(
        Manufacture,
        on_delete=models.CASCADE
    )
    photo_main = models.ImageField(
        _("Main Image"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        default=''
    )
    photo_1 = models.ImageField(
        _("Image 1"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        blank=True
    )
    photo_2 = models.ImageField(
        _("Image 2"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        blank=True
    )
    photo_3 = models.ImageField(
        _("Image 3"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        blank=True
    )
    photo_4 = models.ImageField(
        _("Image 4"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        blank=True
    )
    photo_5 = models.ImageField(
        _("Image 5"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        blank=True
    )
    photo_6 = models.ImageField(
        _("Image 6"),
        upload_to=os.path.join(
            MEDIA_ROOT, 'photos/vendors/products/%Y/%m/%d/'),
        blank=True
    )
    created = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ['id', 'created']

    def __str__(self):
        return self.name

django_project/content/forms.py
# coding: utf-8
from datetime import datetime


__author__ = 'Alison Mukoma <mukomalison@gmail.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__doc__ = ''
__license__ = ''
__copyright__ = ''

from django import forms

django_project/content/views/download_smartcare.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'


from django.views.generic import TemplateView

class DownloadFile(TemplateView):
    template_name = 'content/download_smartcare.html'

django_project/content/views/home.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'

import random
from django.views.generic import TemplateView

from ..models.success_story import SuccessStory
from ..models.sponsors import Partner
from ..models.smartcare import ProjectSummery


class HomeView(TemplateView):
    template_name = 'content/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        success_qs = SuccessStory.objects.filter(published=True)[:3]
        context['recent_stories'] = success_qs

        partner_qs = Partner.objects.filter(partner_type="PT")
        sponsor_qs = Partner.objects.filter(partner_type="SP")
        partner_list = list(partner_qs)
        sponsor_list = list(sponsor_qs)
        try:
            random_partners = list(random.sample(partner_list,
                                               len(partner_list)))
            random_sponsors = list(random.sample(sponsor_list,
                                               len(sponsor_list)))
            foreword_qs = []
            project_overview = ProjectSummery.objects.get(active_on_site=True)

        except:
            random_partners = []
            random_sponsors = []
            foreword_qs = ''
            project_overview = ''

        context['foreword'] = foreword_qs
        context['partners'] = random_partners
        context['sponsors'] = random_sponsors
        context['summery'] = project_overview

        return context


class AboutUsView(TemplateView):
    template_name = 'content/about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutUsView, self).get_context_data(**kwargs)
        try:
            aboutus_qs = []
            foreword_qs = []
        except:
            aboutus_qs = ''
            foreword_qs = ''
        context['aboutus'] = ''
        context['foreword'] = []

        return context

django_project/content/views/smartcare.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'

from django.views.generic import TemplateView

from ..models.smartcare import (
    Overview,
    FunctionalModules,
    TechnologyStack,
    DevelopmentPipeline,
    TechnicalUpdates,
    Deployment,
    Training,
    )

class OverviewView(TemplateView):
    template_name = 'content/overview.html'

    def get_context_data(self, **kwargs):
        context = super(OverviewView, self).get_context_data(**kwargs)
        try:
            qs = Overview.objects.get(published=True)
        except:
            qs = ''
        context['overview'] = qs

        return context


class FunctionalModulesView(TemplateView):
    template_name = 'content/functional_modules.html'

    def get_context_data(self, **kwargs):
        context = super(FunctionalModulesView, self).get_context_data(**kwargs)
        try:
            qs = FunctionalModules.objects.get(published=True)
        except:
            qs = ''
        context['functional_modules'] = qs

        return context



class TechnologyStackView(TemplateView):
    template_name = 'content/technology_stack.html'

    def get_context_data(self, **kwargs):
        context = super(TechnologyStackView, self).get_context_data(**kwargs)
        try:
            qs = TechnologyStack.objects.get(published=True)
        except:
            qs = ''
        context['technology_stack'] = qs

        return context



class DevelopmentPipelineView(TemplateView):
    template_name = 'content/development_pipeline.html'

    def get_context_data(self, **kwargs):
        context = super(DevelopmentPipelineView, self).get_context_data(**kwargs)
        try:
            qs = DevelopmentPipeline.objects.get(published=True)
        except:
            qs = ''
        context['development_pipeline'] = qs

        return context



class TechnicalUpdatesView(TemplateView):
    template_name = 'content/technical_updates.html'

    def get_context_data(self, **kwargs):
        context = super(TechnicalUpdatesView, self).get_context_data(**kwargs)
        try:
            qs = TechnicalUpdates.objects.get(published=True)
        except:
            qs = ''
        context['technical_updates'] = qs

        return context



class DeploymentView(TemplateView):
    template_name = 'content/deployment.html'

    def get_context_data(self, **kwargs):
        context = super(DeploymentView, self).get_context_data(**kwargs)
        try:
            qs = Deployment.objects.get(published=True)
        except:
            qs = ''
        context['deployment'] = qs

        return context



class TrainingView(TemplateView):
    template_name = 'content/training.html'

    def get_context_data(self, **kwargs):
        context = super(TrainingView, self).get_context_data(**kwargs)
        try:
            qs = Training.objects.get(published=True)
        except:
            qs = ''
        context['training'] = qs

        return context

django_project/content/views/sponsors.py
# coding: utf-8
from datetime import datetime


__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'


from ..models.smartcare import Hub

from django.views.generic import TemplateView

from ..models.sponsors import Partner

class SponsorPartnerView(TemplateView):
    template_name = 'content/sponsor_partner_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SponsorPartnerView, self).get_context_data(**kwargs)
        try:
            hubs_qs = Hub.objects.filter(published=True)
            orgnanisation_qs = Partner.objects.all()
        except:
            hubs_qs = ''
            orgnanisation_qs = ''

        context['hubs'] = hubs_qs
        context['orgs'] = orgnanisation_qs

        return context

django_project/content/views/success_story.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'

from django.views.generic import ListView, DetailView

from ..models.success_story import SuccessStory
from ..models.category import Category

class SuccessStoryList(ListView):
    template_name = 'content/success_stories_list.html'
    model = SuccessStory

    def get_context_data(self, **kwargs):
        context = super(SuccessStoryList, self).get_context_data(**kwargs)

        success_qs = SuccessStory.objects.filter(published=True)
        recent_success_qs = SuccessStory.objects.filter(published=True)[:5]

        category_qs = Category.objects.all()[:5]
        context['categories'] = category_qs
        context['success_stories'] = success_qs
        context['recent_stories'] = recent_success_qs

        return context


class SuccessStoryDetail(ListView):

    template_name = 'content/success_story_detail.html'
    model = SuccessStory

    def get_context_data(self, **kwargs):
        context = super(SuccessStoryDetail, self).get_context_data(**kwargs)

        self.story_pk = self.kwargs.get('story_pk', None)
        self.story_qs = SuccessStory.objects.get(pk=self.story_pk)
        context['story'] = self.story_qs

        return context

django_project/content/views/under_development.py
# coding: utf-8
from datetime import datetime

__author__ = 'Alison Mukoma <AMukoma@brhc.com>'
__revision__ = ':%H$'
__date__ = ('%s' % (datetime.now()))
__license__ = ''
__copyright__ = 'Broadreach Corperation'

from django.views.generic import TemplateView

class UnderDevelopment(TemplateView):
    template_name = 'under_development.html'

django_project/content/templates/content/about.html
{% extends "layouts.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block content %}
  <div id="wrapper">
  <section id="inner-headline">
    <div class="container">
      <div class="row">
        <div class="span4">
          <div class="inner-heading">
            <h2>More Insight</h2>
          </div>
        </div>
        <div class="span8">
          <ul class="breadcrumb">
            <li><a href="index.html">Home</a> <i class="icon-angle-right"></i></li>
            <li><a href="#">Pages</a> <i class="icon-angle-right"></i></li>
            <li class="active">About us</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section id="content">
    <div class="container">
      <div class="row">

        <div class="span6">
          <h4>{{ aboutus.title|upper }}</h4>
          <p class="d-inline p-2">
            {{ aboutus.content|safe }}
          </p>

        </div>

        <div class="span6">

          <div class="clearfix"></div>
            <aside class="right-sidebar">

              <div class="widget">
                <h5 class="widgetheading" style="color: black;font-weight: normal !important;font-size: 2.4em !important; margin-bottom: 30px;">{{ foreword.title }}<span></span></h5>
                <img class="img-responsive img-circle pull-right" src="{% thumbnail foreword.photo 400x400 crop %}" style="margin-top: -10pt"/></a>
                  <blockquote>
                    {{ foreword.content|safe }}
                  </blockquote>
              </div>
            </aside>
        </div>
      </div>

      <!-- divider -->
      <div class="row">
        <div class="span12">
          <div class="solidline"></div>
        </div>
      </div>
      <!-- end divider -->
    </div>
  </section>
</div>

{% endblock content %}

django_project/content/templates/content/dashboard.html
{% extends "layouts.html" %}
{% load staticfiles %}
{% block content %}
<div class="wrapper">
  <section id="inner-headline">
    <div class="container">
      <div class="row">
        <div class="span6">
          <div class="inner-heading">
            <h2> SmartCare User statistics Dashboard</h2>
          </div>
        </div>
        <div class="span6">
          <ul class="breadcrumb">
            <li><a href="index.html">Home</a> <i class="icon-angle-right"></i></li>
            <li><a href="#">smartcare</a> <i class="icon-angle-right"></i></li>
            <li class="active">Website statistics</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

    <div id="tracking-filters">
        <form method="GET">
            {{ form.as_table }}
            <input type="submit" name="submit" value="submit" />
        </form>
    </div>
    <div id="tracking-info">
        <p>
            Visitor tracking began on
            {{ track_start_time|date:"Y-m-d H:i:s" }}
        </p>
        {% if warn_incomplete %}
        <p class=warning>
            The start time precedes the oldest tracked visitor, thus
            the stats are not complete for the specified range.
        </p>
        {% endif %}
    </div>
    <div id="tracking-stats">
        {% include "tracking/snippets/stats.html" %}
    </div>
</div>
{% endblock content %}

django_project/content/templates/content/home.html
{% extends "layouts.html" %}
{% load staticfiles %}
{% load thumbnail %}
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{% block content %}
<!-- section intro -->
<!-- <section id="intro">
  <div class="intro-content">
    <h5 style="color:white; font-weight:bold">Pricetag <i class="icon-stethoscope" style="color:white; font-weight:bold"></i></h5>
    <p style="color:white">Find anything you need</p>
    <div style="margin-bottom: -40pt;">
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalLong">
        Wondering what we are?
      </button>

      <style>
        button{
              color: #84c75b;
              }
        a, a:hover, a:active, a:visited, a:focus {
                    text-decoration:none;
                  }
      </style>
    </div>

</div>
</section> -->

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title center" id="exampleModalLongTitle" style="color:#A9A9A9">{{ summery.title|title }}</h5>
      </div>
      <div class="modal-body" style="color:#C0C0C0 background-color:silver">
        {{ summery.content|safe|truncatechars:900 }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

 <style>
      .modal-backdrop {
          z-index: 100000 !important;
        }

     .modal {
           z-index: 100001 !important;
         }

  </style>


<!-- /section intro -->

<section id="content">
  <div class="container">

    <div class="row">
        <div class="span3">
          <div class="row">
            <canvas id="bar-chart" width="1000" height="1500"></canvas>

            <script>
                  new Chart(document.getElementById("bar-chart"), {
                    type: 'polarArea',
                    data: {
                      labels: ["Construction", "Mining", "Electronics", "Home & Garden", "Fashion", "Real Estate"],
                      datasets: [
                        {
                          label: "Brands",
                          backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850", "#f1c40f"],
                          data: [130,233,293,354,430,500],
                          fill: false
                        }
                      ]
                    },
                    options: {
                      legend: { display: false },
                      title: {
                        display: true,
                        text: 'Industries we cover'
                      }
                    }
                });
            </script>
          </div>
        </div>

          <div class="span9">
            <div class="aligncenter">
              <h3 style="color: black;font-weight: normal !important;font-size: 2.3em !important; margin-bottom: 30px;">RECENT GOODS</h3>
            </div>

        <div class="row">
        {% for recent in recent_stories %}
              <div class="span3">
                <div class="pricing-box-plain">
                  <div>
                    <p><b>
                      <a href="{% url 'content:success_detail' story_pk=recent.id %}">
                        {{ recent.title }}
                      </a>
                      </b>
                    </p>
                    <i><small>Published on: {{ recent.updated|date:"M, d, Y"}}</small></i>
                  </div>

                  <div class="desc">
                    <ul>
                      <p>
                      <small>
                          {{ recent.content|truncatechars:240|safe }}
                      </small>
                      </p>
                    </ul>
                  </div>
                  <div class="action">
                    <a href="{% url 'content:success_detail' story_pk=recent.id %}" class="btn btn-info">View more</a>
                  </div>
                </div>
              </div>
          {% endfor %}
        </div>
        <!-- ============= -->
      </div>
    </div>
  </div>  <!-- ==close row wrapper=========== -->
  <!-- </div> -->
</section>
<section id="offer">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="row">
          <div class="aligncenter">
            <h3 style="color: black;font-weight: normal !important;font-size: 2.2em !important; margin-bottom: 30px;">INDUSTRIES</h3>
          </div>
          <!-- style="color:#84c75b;"  -->
            {% for partner in sponsors %}
            <div class="span2">
              <div class="box aligncenter">
                <div class="icon">
                  <img src="{{ partner.logo.url }}" class="img-responsive img-rounded" height='120' width='152' alt="{{ partner.name|upper }}"/>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>



    <div class="row">
      <div class="span12">
        <div class="row">
          <div class="aligncenter">
            <h3 style="color: black;font-weight: normal !important;font-size: 1.8em !important; margin-bottom: 30px;">OUR COMPANY BRANDS</h3>
          </div>
          <!-- style="color:#84c75b;"  -->
            {% for partner in partners %}
            <div class="span2">
              <div class="box aligncenter">
                <div class="icon">
                  <img src="{{ partner.logo.url }}" class="img-responsive img-rounded" height='120' width='152' alt="{{ partner.name|upper }}"/>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>
      </div>
    </div>

  </div>
</section>

{% endblock content %}

django_project/content/templates/content/success_stories_list.html
{% extends "layouts.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block content %}

    <div id="wrapper">
      <!-- start header -->

      <section id="inner-headline">
        <div class="container">
          <div class="row">
            <div class="span4">
              <div class="inner-heading">
                <h2>All Products </h2>
              </div>
            </div>
            <div class="span8">
              <ul class="breadcrumb">
                <li><a href="/">Home</a> <i class="icon-angle-right"></i></li>
                <li class="active">All Products</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section id="content">
        <div class="container">
          <div class="row">

            <div class="span4">

              <aside class="left-sidebar">

                <div class="widget">
                  <form>
                    <div class="input-append">
                      <input class="span2" id="appendedInputButton" type="text" placeholder="Type here">
                      <button class="btn btn-color" type="submit">Search</button>
                    </div>
                  </form>
                </div>

                <div class="widget">

                  <h5 class="widgetheading">Brands</h5>
                  {% for category in categories %}
                  <ul class="cat">
                    <li><i class="icon-angle-right"></i> <a href="#">{{ category|title }}</a><span> (20)</span></li>
                  </ul>
                  {% endfor %}
                </div>

                <div class="widget">

                  <h5 class="widgetheading">Most Selling</h5>
                  <ul class="cat">
                    {% for rstory in recent_stories %}
                    <li><i class="icon-angle-right"></i> <a href="#">{{ rstory.title|title|truncatechars:30 }}</a></li>
                    {% endfor %}
                  </ul>
                </div>

                <!-- <div class="widget">

                  <h5 class="widgetheading">Text widget</h5>
                  <p>
                    Lorem ipsum dolor sit amet, quo everti torquatos rationibus an, graeci splendide mel cu. Sed ad vidisse eruditi maluisset, et duo mazim placerat adipiscing.
                  </p>

                </div> -->
              </aside>
            </div>

            <div class="span8">

              {% for success in success_stories %}

              <article>
                <div class="row">

                  <div class="span8">
                    <div class="post-quote">
                      <div class="post-heading">
                        <h6><a href="{% url 'content:success_detail' story_pk=success.id %}" style="color:grey">{{ success.title }}</a></h6>
                      </div>


                    </div>
                    <div class="meta-post">
                      <a href="#" class="author">By<br /> {{ success.author|truncatechars:10 }}</a>
                      <a href="#" class="date">{{ success.created|date:"M d" }}<br /> {{ success.created|date:"Y" }}</a>
                    </div>
                    <div class="post-entry">
                      <img class="img-responsive img-circle pull-right" src="{% thumbnail success.photo 200x100 crop %}" style="margin-top: -10pt"/></a>

                      <blockquote>
                        {{ success.content|safe|truncatechars:137 }}
                      </blockquote>

                      <a href="{% url 'content:success_detail' story_pk=success.id %}" class="btn btn-color"><i class="icon-tags"> {{ success.category }} |</i> Read more <i class="icon-angle-right"></i></a>
                    </div>

                  </div>
                </div>
              </article>

              {% endfor %}



              <div id="pagination">
                <span class="all">Page 1 of 3</span>
                <span class="current">1</span>
                <a href="#" class="inactive">2</a>
                <a href="#" class="inactive">3</a>
              </div>
            </div>
          </div>
        </div>
      </section>


    </div>
    <a href="#" class="scrollup"><i class="icon-angle-up icon-rounded icon-bglight icon-2x"></i></a>

{% endblock content %}